/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pos.university.ui;

import com.pos.ui.panels.AboutPanel;
import com.pos.ui.panels.ActivityPanel;
import com.pos.ui.panels.AdminPanelLogin;
import com.pos.ui.panels.Adminlogin;
import com.pos.ui.panels.HomePanel;
import com.pos.ui.panels.StaffPanel;
import com.pos.ui.panels.StudentPanel;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.*;  
import javax.swing.JFrame;  
import javax.swing.JPanel;

/**
 *
 * @author LENOVO
 */
public class UniHome extends javax.swing.JFrame {
    ImageIcon exiticIcon = new ImageIcon("exitTheApp.png");
    /**
     * Creates new form UniHome
     */
    Color defaultColor, clickedColor;
    public UniHome() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
//        exit.setIcon(resizeExit(exiticIcon));
        defaultColor = new Color(13,36,51);
        clickedColor = new Color(255,102,0);
        // setting default colors 
        home.setBackground(defaultColor);
        admin.setBackground(defaultColor);
        student.setBackground(defaultColor);
        staff.setBackground(defaultColor);
        activities.setBackground(defaultColor);
        aboutus.setBackground(defaultColor);
        // Default selected page
        selected.setText("Home");
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        admin = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        student = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        staff = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        activities = new javax.swing.JPanel();
        Activities = new javax.swing.JLabel();
        aboutus = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        selected = new javax.swing.JLabel();
        exit = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        displayPanel = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BIOLA - Home");

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(13, 36, 51));

        home.setBackground(new java.awt.Color(13, 36, 51));
        home.setPreferredSize(new java.awt.Dimension(0, 36));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
        });
        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Home");
        home.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 90, 30));

        admin.setBackground(new java.awt.Color(13, 36, 51));
        admin.setPreferredSize(new java.awt.Dimension(0, 36));
        admin.setRequestFocusEnabled(false);
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                adminMousePressed(evt);
            }
        });
        admin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Admin");
        admin.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 80, 30));

        student.setBackground(new java.awt.Color(13, 36, 51));
        student.setPreferredSize(new java.awt.Dimension(0, 36));
        student.setRequestFocusEnabled(false);
        student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                studentMousePressed(evt);
            }
        });
        student.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Student");
        student.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 80, 30));

        staff.setBackground(new java.awt.Color(13, 36, 51));
        staff.setPreferredSize(new java.awt.Dimension(0, 36));
        staff.setRequestFocusEnabled(false);
        staff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                staffMousePressed(evt);
            }
        });
        staff.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Staff");
        staff.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 80, 30));

        activities.setBackground(new java.awt.Color(13, 36, 51));
        activities.setPreferredSize(new java.awt.Dimension(0, 36));
        activities.setRequestFocusEnabled(false);
        activities.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                activitiesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                activitiesMousePressed(evt);
            }
        });
        activities.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Activities.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        Activities.setForeground(new java.awt.Color(255, 255, 255));
        Activities.setText("Activities");
        activities.add(Activities, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 80, 30));

        aboutus.setBackground(new java.awt.Color(13, 36, 51));
        aboutus.setPreferredSize(new java.awt.Dimension(0, 36));
        aboutus.setRequestFocusEnabled(false);
        aboutus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutusMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutusMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aboutusMousePressed(evt);
            }
        });
        aboutus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("About us");
        aboutus.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 80, 30));

        selected.setBackground(new java.awt.Color(255, 102, 0));
        selected.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        selected.setForeground(new java.awt.Color(255, 255, 255));
        selected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selected.setOpaque(true);

        exit.setBackground(new java.awt.Color(13, 36, 51));
        exit.setPreferredSize(new java.awt.Dimension(0, 36));
        exit.setRequestFocusEnabled(false);
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });
        exit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Exit");
        exit.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 80, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(aboutus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(activities, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(staff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(student, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(admin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)))
            .addComponent(selected, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(selected, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(student, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(staff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(activities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(aboutus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout displayPanelLayout = new javax.swing.GroupLayout(displayPanel);
        displayPanel.setLayout(displayPanelLayout);
        displayPanelLayout.setHorizontalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 823, Short.MAX_VALUE)
        );
        displayPanelLayout.setVerticalGroup(
            displayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(displayPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMousePressed
        // TODO add your handling code here:
        home.setBackground(clickedColor);
        admin.setBackground(defaultColor);
        student.setBackground(defaultColor);
        staff.setBackground(defaultColor);
        activities.setBackground(defaultColor);
        aboutus.setBackground(defaultColor);
        
        selected.setText("Home");
    }//GEN-LAST:event_homeMousePressed

    private void adminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMousePressed
        // TODO add your handling code here:
        home.setBackground(defaultColor);
        admin.setBackground(clickedColor);
        student.setBackground(defaultColor);
        staff.setBackground(defaultColor);
        activities.setBackground(defaultColor);
        aboutus.setBackground(defaultColor);
        selected.setText("Admin");
    }//GEN-LAST:event_adminMousePressed

    private void studentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentMousePressed
        // TODO add your handling code here:
        home.setBackground(defaultColor);
        admin.setBackground(defaultColor);
        student.setBackground(clickedColor);
        staff.setBackground(defaultColor);
        activities.setBackground(defaultColor);
        aboutus.setBackground(defaultColor);
        selected.setText("Student");
    }//GEN-LAST:event_studentMousePressed

    private void staffMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffMousePressed
        // TODO add your handling code here:
        home.setBackground(defaultColor);
        admin.setBackground(defaultColor);
        student.setBackground(defaultColor);
        staff.setBackground(clickedColor);
        activities.setBackground(defaultColor);
        aboutus.setBackground(defaultColor);
        selected.setText("Staff");
    }//GEN-LAST:event_staffMousePressed

    private void activitiesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activitiesMousePressed
        // TODO add your handling code here:
        home.setBackground(defaultColor);
        admin.setBackground(defaultColor);
        student.setBackground(defaultColor);
        staff.setBackground(defaultColor);
        activities.setBackground(clickedColor);
        aboutus.setBackground(defaultColor);
        selected.setText("Activities");
    }//GEN-LAST:event_activitiesMousePressed

    private void aboutusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutusMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutusMouseExited

    private void aboutusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutusMousePressed
        // TODO add your handling code here:
        home.setBackground(defaultColor);
        admin.setBackground(defaultColor);
        student.setBackground(defaultColor);
        staff.setBackground(defaultColor);
        activities.setBackground(defaultColor);
        aboutus.setBackground(clickedColor);
        selected.setText("About us");
    }//GEN-LAST:event_aboutusMousePressed

    @Override
    public void print(Graphics g) {
        super.print(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }
   private JFrame jFrame1;
    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        HomePanel homePanel = new HomePanel();
        displayPanel.removeAll();
        displayPanel.add(homePanel).setVisible(true);
    }//GEN-LAST:event_homeMouseClicked

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked
        // TODO add your handling code here:
        Adminlogin admin = new Adminlogin();
        displayPanel.removeAll();
        displayPanel.add(admin).setVisible(true);
            
    }//GEN-LAST:event_adminMouseClicked
    public  void changeFrame(boolean status){
        UniStudent student = new UniStudent();
        student.show();
    }
    private void studentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentMouseClicked
        // TODO add your handling code here:
        StudentPanel student = new StudentPanel();
        displayPanel.removeAll();
        displayPanel.add(student).setVisible(true);
    }//GEN-LAST:event_studentMouseClicked

    private void staffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffMouseClicked
        // TODO add your handling code here:
        StaffPanel staff = new StaffPanel();
        displayPanel.removeAll();
        displayPanel.add(staff).setVisible(true);
    }//GEN-LAST:event_staffMouseClicked

    @Override
    public void printAll(Graphics g) {
        super.printAll(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }
    public void activ(){
        ActivityPanel activity = new ActivityPanel();
        displayPanel.removeAll();
        displayPanel.add(activity).setVisible(true);
    }
    private void activitiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activitiesMouseClicked
        // TODO add your handling code here:
        activ();
    }//GEN-LAST:event_activitiesMouseClicked
    //  TEST 
    public JPanel dispPanel(){
        return displayPanel;
    }
    private void aboutusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutusMouseClicked
        // TODO add your handling code here:
        AboutPanel about = new AboutPanel();
        displayPanel.removeAll();
        displayPanel.add(about).setVisible(true);
    }//GEN-LAST:event_aboutusMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseExited

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitMousePressed

    private void adminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_adminMouseEntered
    private JFrame jFrame;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UniHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UniHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UniHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UniHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UniHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Activities;
    private javax.swing.JPanel aboutus;
    private javax.swing.JPanel activities;
    private javax.swing.JPanel admin;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JPanel exit;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel selected;
    private javax.swing.JPanel staff;
    private javax.swing.JPanel student;
    // End of variables declaration//GEN-END:variables
}
